// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIDzqSWH7Sow4WZOOFjouOWjozacYMU_w',
    appId: '1:373704524087:android:10f553c389d922f361dab2',
    messagingSenderId: '373704524087',
    projectId: 'priloco-ea3f4',
    storageBucket: 'priloco-ea3f4.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZtLoVwDEOdML8DKSnokzZZNYjbzERP1A',
    appId: '1:373704524087:web:a1314942dddc2ef561dab2',
    messagingSenderId: '373704524087',
    projectId: 'priloco-ea3f4',
    authDomain: 'priloco-ea3f4.firebaseapp.com',
    storageBucket: 'priloco-ea3f4.appspot.com',
    measurementId: 'G-WTBCYYG01G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTBFtO3-zxUQJzbSFmsi3yrECs0M7du8',
    appId: '1:373704524087:ios:b2aa9fa05e47943d61dab2',
    messagingSenderId: '373704524087',
    projectId: 'priloco-ea3f4',
    storageBucket: 'priloco-ea3f4.appspot.com',
    iosBundleId: 'com.example.bonsplans',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTBFtO3-zxUQJzbSFmsi3yrECs0M7du8',
    appId: '1:373704524087:ios:3642943f5aaa33b861dab2',
    messagingSenderId: '373704524087',
    projectId: 'priloco-ea3f4',
    storageBucket: 'priloco-ea3f4.appspot.com',
    iosBundleId: 'com.company.priloco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZtLoVwDEOdML8DKSnokzZZNYjbzERP1A',
    appId: '1:373704524087:web:c1cad08e3613636861dab2',
    messagingSenderId: '373704524087',
    projectId: 'priloco-ea3f4',
    authDomain: 'priloco-ea3f4.firebaseapp.com',
    storageBucket: 'priloco-ea3f4.appspot.com',
    measurementId: 'G-0W4ED2PHJK',
  );

}